#!/usr/bin/env bash

#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4G
#SBATCH --time=20:00:00
#SBATCH --job-name=fastqc
#SBATCH --mail-user=zhihui.wang@students.unibe.ch
#SBATCH --mail-type=begin,end
#SBATCH --output=/data/users/zwang/new_assembly/output/output_fastqc_%j.o
#SBATCH --error=/data/users/zwang/new_assembly/output/error_fastqc_%j.e
#SBATCH --partition=pibu_el8


Data_PATH=/data/users/zwang/new_assembly/participant_7
QC_out=/data/users/zwang/new_assembly/01_fastqc


module load FastQC/0.11.9-Java-11

cd $Data_PATH
for i in *;do
	cd ${i}
	mkdir $QC_out/${i}
	fastqc -o $QC_out/${i} *.gz
	cd ../
done
