#!/usr/bin/env bash

#SBATCH --time=2-00:00:00
#SBATCH --mem=100
#SBATCH --cpus-per-task=8
#SBATCH --job-name=04_polish_flye
#SBATCH --mail-user=zhihui.wang@students.unibe.ch
#SBATCH --mail-type=begin,end
#SBATCH --output=/data/users/zwang/new_assembly/output/output_04_polish_flye_%j.o
#SBATCH --error=/data/users/zwang/new_assembly/output/error_04_polish_flye_%j.e
#SBATCH --partition=pgpu


module load Bowtie2/2.4.4-GCC-10.3.0
module load SAMtools/1.13-GCC-10.3.0
module load Pilon/1.23-Java-11
module load FastQC/0.11.9-Java-11q

draft_genome=/data/users/zwang/new_assembly/03_flye
data=/data/users/zwang/new_assembly/participant_7/Illumina
outfile=/data/users/zwang/new_assembly/04_flye_polish
cd $draft_genome
# comparation
bowtie2-build -f  assembly.fasta --threads 8 z | bowtie2 \
 -x \
   --sensitive-local \
   -p 8 \
   -1 $data*1.fq.gz \
   -2 $data*2.fq.gz | samtools sort \  
   -T $SCRATCH \
  -@ $SLURM_CPUS_PER_TASK \
    -O bam \
aln.sam \    -o last.sorted.bam
samtools index -b -@ 8 last.sorted.bam

java -Xmx45g -jar $EBROOTPILON/pilon-1.23.jar \
    --genome $draft_genome/*fasta\
    --bam last.sorted.bam \
    --outdir $outfile \
    --threads 8
