#!/usr/bin/env bash

#SBATCH --time=2-00:00:00
#SBATCH --mem=100G
#SBATCH --cpus-per-task=8
#SBATCH --job-name=05_busco
#SBATCH --mail-user=zhihui.wang@students.unibe.ch
#SBATCH --mail-type=begin,end
#SBATCH --output=/data/users/zwang/new_assembly/output/output_05_busco_%j.o
#SBATCH --error=/data/users/zwang/new_assembly/output/error_05_busco_%j.e
#SBATCH --partition=pgpu

# busco polished flye and canu #

WORKDIR=/data/users/zwang/new_assembly
OUTDIR=$WORKDIR/05_busco

# flye
apptainer exec --bind ${WORKDIR}/04_flye_polish/ /data/courses/assembly-annotation-course/containers2/busco_v5.1.2_cv1.sif busco --cpu 4 -m genome -i ${WORKDIR}/04_flye_polish/pilon.fasta -oflye -l brassicales_odb10

# canu
apptainer exec --bind ${WORKDIR}/04_canu_polish/ /data/courses/assembly-annotation-course/containers2/busco_v5.1.2_cv1.sif busco --cpu 4 -m genome -i ${WORKDIR}/04_canu_polish/pilon.fasta -o canu  -l brassicales_odb10

# RNA_seq
apptainer exec --bind ${WORKDIR}/03_trinity/ /data/courses/assembly-annotation-course/containers2/busco_v5.1.2_cv1.sif busco --cpu 4 -m genome -i ${WORKDIR}/03_trinity/03_trinity.Trinity.fasta -o trinity  -l brassicales_odb10
